# Build settings
source: source
destination: _site
exclude:
  - sass
  - javascript-pretty
  - css-pretty
excerpt_separator: "

"

# Site settings
title: neurotischism
description: "this is a description"

domain: neurotischism.com
url: "http://neurotischism.com"
author: elliot hatch
email: elliot@neurotischism.com
twitter: neurotischism
github: elliothatch

permalink: /:categories/:title/

# Build settings
#markdown: kramdown
#permalink: pretty
